version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d auth_db -U admin"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    networks:
      - my_network
    volumes:
      - pgdata:/var/lib/postgresql/data


networks:
  my_network:
    driver: bridge

volumes:
  pgdata:

